### ISSUE TITLE
Send SMS using Windows command line

### ISSUE THREAD

**Issue by modest1981** [manoaratefy/huawei-e8372-api#1]
Hello dear,
Thanks for your efforts on this code.
Could you kindly advise how to send SMS using Windows command line PHP?
I need the exact commands to call the send SMS functions as well as defining my modem IP and user/pass.

**Comment by manoaratefy** [comment]
You can use following code (replace `0123456789` with your destination number, and also put your credentials on the class construction):

```
<?php

require_once('vendor/autoload.php');
require_once('modem.class.php');

$modem1 = new Manoaratefy\NetworkTools\Modem('192.168.8.1', 'admin', 'password');

if (!$modem1->online()) {
    echo "The modem is not online. Check network connection.\n";
}

$modem1->smssend('0123456789', 'This is the first SMS sent from my PC using API.');
```

**Comment by modest1981** [comment]
Thanks for your quick answer.

So far so good. I managed to send my first SMS. Now I have two other issues:

1. Do you know how to insert a new line in SMS text? When I use \n, it doesn't work.
2. Could you kindly help me compose a single URL to pass the "phone number" and "sms text" to my PHP server?

My Scenario : 
I want to use this as an SMS alerting system on my Arduino board according to the below flow.

Arduino board  ------>   My PHP server   ------>   E8372 modem

1. Arduino GET a single URL passing the "phone number" and "sms text" to my PHP server.
2. My PHP server calls the E8372 (with the help of this code).
3. E8372 modem sends the alert SMS to admin.

Sorry, I'm a rookie and I know this may not be a good place to discuss this.
